//file: Hubris/HMatrix/HMatrixOperatorImp.cxx

/**/
#define HMATRIX_OPERATOR_WIDTH	1
#define HMATRIX_OPERATOR_HEIGHT	1
#define HMATRIX_OPERATOR_PARAM	HMATRIX_OPERATOR_TYPE, HMATRIX_OPERATOR_WIDTH, HMATRIX_OPERATOR_HEIGHT

#include "Hubris/HMatrix/HMatrixOperatorImpStandard.hxx"

#undef HMATRIX_OPERATOR_WIDTH
#undef HMATRIX_OPERATOR_HEIGHT
#undef HMATRIX_OPERATOR_PARAM	

/**/
#define HMATRIX_OPERATOR_WIDTH	2
#define HMATRIX_OPERATOR_HEIGHT	1
#define HMATRIX_OPERATOR_PARAM	HMATRIX_OPERATOR_TYPE, HMATRIX_OPERATOR_WIDTH, HMATRIX_OPERATOR_HEIGHT

#include "Hubris/HMatrix/HMatrixOperatorImpStandard.hxx"

#undef HMATRIX_OPERATOR_WIDTH
#undef HMATRIX_OPERATOR_HEIGHT
#undef HMATRIX_OPERATOR_PARAM	

/**/
#define HMATRIX_OPERATOR_WIDTH	3
#define HMATRIX_OPERATOR_HEIGHT	1
#define HMATRIX_OPERATOR_PARAM	HMATRIX_OPERATOR_TYPE, HMATRIX_OPERATOR_WIDTH, HMATRIX_OPERATOR_HEIGHT

#include "Hubris/HMatrix/HMatrixOperatorImpStandard.hxx"

#undef HMATRIX_OPERATOR_WIDTH
#undef HMATRIX_OPERATOR_HEIGHT
#undef HMATRIX_OPERATOR_PARAM	

/**/
#define HMATRIX_OPERATOR_WIDTH	4
#define HMATRIX_OPERATOR_HEIGHT	1
#define HMATRIX_OPERATOR_PARAM	HMATRIX_OPERATOR_TYPE, HMATRIX_OPERATOR_WIDTH, HMATRIX_OPERATOR_HEIGHT

#include "Hubris/HMatrix/HMatrixOperatorImpStandard.hxx"

#undef HMATRIX_OPERATOR_WIDTH
#undef HMATRIX_OPERATOR_HEIGHT
#undef HMATRIX_OPERATOR_PARAM	

/**/
#define HMATRIX_OPERATOR_WIDTH	5
#define HMATRIX_OPERATOR_HEIGHT	1
#define HMATRIX_OPERATOR_PARAM	HMATRIX_OPERATOR_TYPE, HMATRIX_OPERATOR_WIDTH, HMATRIX_OPERATOR_HEIGHT

#include "Hubris/HMatrix/HMatrixOperatorImpStandard.hxx"

#undef HMATRIX_OPERATOR_WIDTH
#undef HMATRIX_OPERATOR_HEIGHT
#undef HMATRIX_OPERATOR_PARAM	

/**/
#define HMATRIX_OPERATOR_WIDTH	1
#define HMATRIX_OPERATOR_HEIGHT	2
#define HMATRIX_OPERATOR_PARAM	HMATRIX_OPERATOR_TYPE, HMATRIX_OPERATOR_WIDTH, HMATRIX_OPERATOR_HEIGHT

#include "Hubris/HMatrix/HMatrixOperatorImpStandard.hxx"

#undef HMATRIX_OPERATOR_WIDTH
#undef HMATRIX_OPERATOR_HEIGHT
#undef HMATRIX_OPERATOR_PARAM	

/**/
#define HMATRIX_OPERATOR_WIDTH	2
#define HMATRIX_OPERATOR_HEIGHT	2
#define HMATRIX_OPERATOR_PARAM	HMATRIX_OPERATOR_TYPE, HMATRIX_OPERATOR_WIDTH, HMATRIX_OPERATOR_HEIGHT

#include "Hubris/HMatrix/HMatrixOperatorImpStandard.hxx"

#undef HMATRIX_OPERATOR_WIDTH
#undef HMATRIX_OPERATOR_HEIGHT
#undef HMATRIX_OPERATOR_PARAM	

/**/
#define HMATRIX_OPERATOR_WIDTH	3
#define HMATRIX_OPERATOR_HEIGHT	2
#define HMATRIX_OPERATOR_PARAM	HMATRIX_OPERATOR_TYPE, HMATRIX_OPERATOR_WIDTH, HMATRIX_OPERATOR_HEIGHT

#include "Hubris/HMatrix/HMatrixOperatorImpStandard.hxx"

#undef HMATRIX_OPERATOR_WIDTH
#undef HMATRIX_OPERATOR_HEIGHT
#undef HMATRIX_OPERATOR_PARAM	

/**/
#define HMATRIX_OPERATOR_WIDTH	4
#define HMATRIX_OPERATOR_HEIGHT	2
#define HMATRIX_OPERATOR_PARAM	HMATRIX_OPERATOR_TYPE, HMATRIX_OPERATOR_WIDTH, HMATRIX_OPERATOR_HEIGHT

#include "Hubris/HMatrix/HMatrixOperatorImpStandard.hxx"

#undef HMATRIX_OPERATOR_WIDTH
#undef HMATRIX_OPERATOR_HEIGHT
#undef HMATRIX_OPERATOR_PARAM	

/**/
#define HMATRIX_OPERATOR_WIDTH	5
#define HMATRIX_OPERATOR_HEIGHT	2
#define HMATRIX_OPERATOR_PARAM	HMATRIX_OPERATOR_TYPE, HMATRIX_OPERATOR_WIDTH, HMATRIX_OPERATOR_HEIGHT

#include "Hubris/HMatrix/HMatrixOperatorImpStandard.hxx"

#undef HMATRIX_OPERATOR_WIDTH
#undef HMATRIX_OPERATOR_HEIGHT
#undef HMATRIX_OPERATOR_PARAM	

/**/
#define HMATRIX_OPERATOR_WIDTH	1
#define HMATRIX_OPERATOR_HEIGHT	3
#define HMATRIX_OPERATOR_PARAM	HMATRIX_OPERATOR_TYPE, HMATRIX_OPERATOR_WIDTH, HMATRIX_OPERATOR_HEIGHT

#include "Hubris/HMatrix/HMatrixOperatorImpStandard.hxx"

#undef HMATRIX_OPERATOR_WIDTH
#undef HMATRIX_OPERATOR_HEIGHT
#undef HMATRIX_OPERATOR_PARAM	

/**/
#define HMATRIX_OPERATOR_WIDTH	2
#define HMATRIX_OPERATOR_HEIGHT	3
#define HMATRIX_OPERATOR_PARAM	HMATRIX_OPERATOR_TYPE, HMATRIX_OPERATOR_WIDTH, HMATRIX_OPERATOR_HEIGHT

#include "Hubris/HMatrix/HMatrixOperatorImpStandard.hxx"

#undef HMATRIX_OPERATOR_WIDTH
#undef HMATRIX_OPERATOR_HEIGHT
#undef HMATRIX_OPERATOR_PARAM	

/**/
#define HMATRIX_OPERATOR_WIDTH	3
#define HMATRIX_OPERATOR_HEIGHT	3
#define HMATRIX_OPERATOR_PARAM	HMATRIX_OPERATOR_TYPE, HMATRIX_OPERATOR_WIDTH, HMATRIX_OPERATOR_HEIGHT

#include "Hubris/HMatrix/HMatrixOperatorImpStandard.hxx"

#undef HMATRIX_OPERATOR_WIDTH
#undef HMATRIX_OPERATOR_HEIGHT
#undef HMATRIX_OPERATOR_PARAM	

/**/
#define HMATRIX_OPERATOR_WIDTH	4
#define HMATRIX_OPERATOR_HEIGHT	3
#define HMATRIX_OPERATOR_PARAM	HMATRIX_OPERATOR_TYPE, HMATRIX_OPERATOR_WIDTH, HMATRIX_OPERATOR_HEIGHT

#include "Hubris/HMatrix/HMatrixOperatorImpStandard.hxx"

#undef HMATRIX_OPERATOR_WIDTH
#undef HMATRIX_OPERATOR_HEIGHT
#undef HMATRIX_OPERATOR_PARAM	

/**/
#define HMATRIX_OPERATOR_WIDTH	5
#define HMATRIX_OPERATOR_HEIGHT	3
#define HMATRIX_OPERATOR_PARAM	HMATRIX_OPERATOR_TYPE, HMATRIX_OPERATOR_WIDTH, HMATRIX_OPERATOR_HEIGHT

#include "Hubris/HMatrix/HMatrixOperatorImpStandard.hxx"

#undef HMATRIX_OPERATOR_WIDTH
#undef HMATRIX_OPERATOR_HEIGHT
#undef HMATRIX_OPERATOR_PARAM	

/**/
#define HMATRIX_OPERATOR_WIDTH	1
#define HMATRIX_OPERATOR_HEIGHT	4
#define HMATRIX_OPERATOR_PARAM	HMATRIX_OPERATOR_TYPE, HMATRIX_OPERATOR_WIDTH, HMATRIX_OPERATOR_HEIGHT

#include "Hubris/HMatrix/HMatrixOperatorImpStandard.hxx"

#undef HMATRIX_OPERATOR_WIDTH
#undef HMATRIX_OPERATOR_HEIGHT
#undef HMATRIX_OPERATOR_PARAM	

/**/
#define HMATRIX_OPERATOR_WIDTH	2
#define HMATRIX_OPERATOR_HEIGHT	4
#define HMATRIX_OPERATOR_PARAM	HMATRIX_OPERATOR_TYPE, HMATRIX_OPERATOR_WIDTH, HMATRIX_OPERATOR_HEIGHT

#include "Hubris/HMatrix/HMatrixOperatorImpStandard.hxx"

#undef HMATRIX_OPERATOR_WIDTH
#undef HMATRIX_OPERATOR_HEIGHT
#undef HMATRIX_OPERATOR_PARAM	

/**/
#define HMATRIX_OPERATOR_WIDTH	3
#define HMATRIX_OPERATOR_HEIGHT	4
#define HMATRIX_OPERATOR_PARAM	HMATRIX_OPERATOR_TYPE, HMATRIX_OPERATOR_WIDTH, HMATRIX_OPERATOR_HEIGHT

#include "Hubris/HMatrix/HMatrixOperatorImpStandard.hxx"

#undef HMATRIX_OPERATOR_WIDTH
#undef HMATRIX_OPERATOR_HEIGHT
#undef HMATRIX_OPERATOR_PARAM	

/**/
#define HMATRIX_OPERATOR_WIDTH	4
#define HMATRIX_OPERATOR_HEIGHT	4
#define HMATRIX_OPERATOR_PARAM	HMATRIX_OPERATOR_TYPE, HMATRIX_OPERATOR_WIDTH, HMATRIX_OPERATOR_HEIGHT

#include "Hubris/HMatrix/HMatrixOperatorImpStandard.hxx"

#undef HMATRIX_OPERATOR_WIDTH
#undef HMATRIX_OPERATOR_HEIGHT
#undef HMATRIX_OPERATOR_PARAM	

/**/
#define HMATRIX_OPERATOR_WIDTH	5
#define HMATRIX_OPERATOR_HEIGHT	4
#define HMATRIX_OPERATOR_PARAM	HMATRIX_OPERATOR_TYPE, HMATRIX_OPERATOR_WIDTH, HMATRIX_OPERATOR_HEIGHT

#include "Hubris/HMatrix/HMatrixOperatorImpStandard.hxx"

#undef HMATRIX_OPERATOR_WIDTH
#undef HMATRIX_OPERATOR_HEIGHT
#undef HMATRIX_OPERATOR_PARAM	

/**/
#define HMATRIX_OPERATOR_WIDTH	1
#define HMATRIX_OPERATOR_HEIGHT	5
#define HMATRIX_OPERATOR_PARAM	HMATRIX_OPERATOR_TYPE, HMATRIX_OPERATOR_WIDTH, HMATRIX_OPERATOR_HEIGHT

#include "Hubris/HMatrix/HMatrixOperatorImpStandard.hxx"

#undef HMATRIX_OPERATOR_WIDTH
#undef HMATRIX_OPERATOR_HEIGHT
#undef HMATRIX_OPERATOR_PARAM	

/**/
#define HMATRIX_OPERATOR_WIDTH	2
#define HMATRIX_OPERATOR_HEIGHT	5
#define HMATRIX_OPERATOR_PARAM	HMATRIX_OPERATOR_TYPE, HMATRIX_OPERATOR_WIDTH, HMATRIX_OPERATOR_HEIGHT

#include "Hubris/HMatrix/HMatrixOperatorImpStandard.hxx"

#undef HMATRIX_OPERATOR_WIDTH
#undef HMATRIX_OPERATOR_HEIGHT
#undef HMATRIX_OPERATOR_PARAM	

/**/
#define HMATRIX_OPERATOR_WIDTH	3
#define HMATRIX_OPERATOR_HEIGHT	5
#define HMATRIX_OPERATOR_PARAM	HMATRIX_OPERATOR_TYPE, HMATRIX_OPERATOR_WIDTH, HMATRIX_OPERATOR_HEIGHT

#include "Hubris/HMatrix/HMatrixOperatorImpStandard.hxx"

#undef HMATRIX_OPERATOR_WIDTH
#undef HMATRIX_OPERATOR_HEIGHT
#undef HMATRIX_OPERATOR_PARAM	

/**/
#define HMATRIX_OPERATOR_WIDTH	4
#define HMATRIX_OPERATOR_HEIGHT	5
#define HMATRIX_OPERATOR_PARAM	HMATRIX_OPERATOR_TYPE, HMATRIX_OPERATOR_WIDTH, HMATRIX_OPERATOR_HEIGHT

#include "Hubris/HMatrix/HMatrixOperatorImpStandard.hxx"

#undef HMATRIX_OPERATOR_WIDTH
#undef HMATRIX_OPERATOR_HEIGHT
#undef HMATRIX_OPERATOR_PARAM	

/**/
#define HMATRIX_OPERATOR_WIDTH	5
#define HMATRIX_OPERATOR_HEIGHT	5
#define HMATRIX_OPERATOR_PARAM	HMATRIX_OPERATOR_TYPE, HMATRIX_OPERATOR_WIDTH, HMATRIX_OPERATOR_HEIGHT

#include "Hubris/HMatrix/HMatrixOperatorImpStandard.hxx"

#undef HMATRIX_OPERATOR_WIDTH
#undef HMATRIX_OPERATOR_HEIGHT
#undef HMATRIX_OPERATOR_PARAM	

/**/
#define HMATRIX_OPERATOR_M	1
#define HMATRIX_OPERATOR_N	1

#include "Hubris/HMatrix/HMatrixOperatorImpMultiplication.hxx"

#undef HMATRIX_OPERATOR_M
#undef HMATRIX_OPERATOR_N

/**/
#define HMATRIX_OPERATOR_M	2
#define HMATRIX_OPERATOR_N	1

#include "Hubris/HMatrix/HMatrixOperatorImpMultiplication.hxx"

#undef HMATRIX_OPERATOR_M
#undef HMATRIX_OPERATOR_N

/**/
#define HMATRIX_OPERATOR_M	3
#define HMATRIX_OPERATOR_N	1

#include "Hubris/HMatrix/HMatrixOperatorImpMultiplication.hxx"

#undef HMATRIX_OPERATOR_M
#undef HMATRIX_OPERATOR_N

/**/
#define HMATRIX_OPERATOR_M	4
#define HMATRIX_OPERATOR_N	1

#include "Hubris/HMatrix/HMatrixOperatorImpMultiplication.hxx"

#undef HMATRIX_OPERATOR_M
#undef HMATRIX_OPERATOR_N

/**/
#define HMATRIX_OPERATOR_M	5
#define HMATRIX_OPERATOR_N	1

#include "Hubris/HMatrix/HMatrixOperatorImpMultiplication.hxx"

#undef HMATRIX_OPERATOR_M
#undef HMATRIX_OPERATOR_N

/**/
#define HMATRIX_OPERATOR_M	1
#define HMATRIX_OPERATOR_N	2

#include "Hubris/HMatrix/HMatrixOperatorImpMultiplication.hxx"

#undef HMATRIX_OPERATOR_M
#undef HMATRIX_OPERATOR_N

/**/
#define HMATRIX_OPERATOR_M	2
#define HMATRIX_OPERATOR_N	2

#include "Hubris/HMatrix/HMatrixOperatorImpMultiplication.hxx"

#undef HMATRIX_OPERATOR_M
#undef HMATRIX_OPERATOR_N

/**/
#define HMATRIX_OPERATOR_M	3
#define HMATRIX_OPERATOR_N	2

#include "Hubris/HMatrix/HMatrixOperatorImpMultiplication.hxx"

#undef HMATRIX_OPERATOR_M
#undef HMATRIX_OPERATOR_N

/**/
#define HMATRIX_OPERATOR_M	4
#define HMATRIX_OPERATOR_N	2

#include "Hubris/HMatrix/HMatrixOperatorImpMultiplication.hxx"

#undef HMATRIX_OPERATOR_M
#undef HMATRIX_OPERATOR_N

/**/
#define HMATRIX_OPERATOR_M	5
#define HMATRIX_OPERATOR_N	2

#include "Hubris/HMatrix/HMatrixOperatorImpMultiplication.hxx"

#undef HMATRIX_OPERATOR_M
#undef HMATRIX_OPERATOR_N

/**/
#define HMATRIX_OPERATOR_M	1
#define HMATRIX_OPERATOR_N	3

#include "Hubris/HMatrix/HMatrixOperatorImpMultiplication.hxx"

#undef HMATRIX_OPERATOR_M
#undef HMATRIX_OPERATOR_N

/**/
#define HMATRIX_OPERATOR_M	2
#define HMATRIX_OPERATOR_N	3

#include "Hubris/HMatrix/HMatrixOperatorImpMultiplication.hxx"

#undef HMATRIX_OPERATOR_M
#undef HMATRIX_OPERATOR_N

/**/
#define HMATRIX_OPERATOR_M	3
#define HMATRIX_OPERATOR_N	3

#include "Hubris/HMatrix/HMatrixOperatorImpMultiplication.hxx"

#undef HMATRIX_OPERATOR_M
#undef HMATRIX_OPERATOR_N

/**/
#define HMATRIX_OPERATOR_M	4
#define HMATRIX_OPERATOR_N	3

#include "Hubris/HMatrix/HMatrixOperatorImpMultiplication.hxx"

#undef HMATRIX_OPERATOR_M
#undef HMATRIX_OPERATOR_N

/**/
#define HMATRIX_OPERATOR_M	5
#define HMATRIX_OPERATOR_N	3

#include "Hubris/HMatrix/HMatrixOperatorImpMultiplication.hxx"

#undef HMATRIX_OPERATOR_M
#undef HMATRIX_OPERATOR_N

/**/
#define HMATRIX_OPERATOR_M	1
#define HMATRIX_OPERATOR_N	4

#include "Hubris/HMatrix/HMatrixOperatorImpMultiplication.hxx"

#undef HMATRIX_OPERATOR_M
#undef HMATRIX_OPERATOR_N

/**/
#define HMATRIX_OPERATOR_M	2
#define HMATRIX_OPERATOR_N	4

#include "Hubris/HMatrix/HMatrixOperatorImpMultiplication.hxx"

#undef HMATRIX_OPERATOR_M
#undef HMATRIX_OPERATOR_N

/**/
#define HMATRIX_OPERATOR_M	3
#define HMATRIX_OPERATOR_N	4

#include "Hubris/HMatrix/HMatrixOperatorImpMultiplication.hxx"

#undef HMATRIX_OPERATOR_M
#undef HMATRIX_OPERATOR_N

/**/
#define HMATRIX_OPERATOR_M	4
#define HMATRIX_OPERATOR_N	4

#include "Hubris/HMatrix/HMatrixOperatorImpMultiplication.hxx"

#undef HMATRIX_OPERATOR_M
#undef HMATRIX_OPERATOR_N

/**/
#define HMATRIX_OPERATOR_M	5
#define HMATRIX_OPERATOR_N	4

#include "Hubris/HMatrix/HMatrixOperatorImpMultiplication.hxx"

#undef HMATRIX_OPERATOR_M
#undef HMATRIX_OPERATOR_N

/**/
#define HMATRIX_OPERATOR_M	1
#define HMATRIX_OPERATOR_N	5

#include "Hubris/HMatrix/HMatrixOperatorImpMultiplication.hxx"

#undef HMATRIX_OPERATOR_M
#undef HMATRIX_OPERATOR_N
/**/
#define HMATRIX_OPERATOR_M	2
#define HMATRIX_OPERATOR_N	5

#include "Hubris/HMatrix/HMatrixOperatorImpMultiplication.hxx"

#undef HMATRIX_OPERATOR_M
#undef HMATRIX_OPERATOR_N
/**/
#define HMATRIX_OPERATOR_M	3
#define HMATRIX_OPERATOR_N	5

#include "Hubris/HMatrix/HMatrixOperatorImpMultiplication.hxx"

#undef HMATRIX_OPERATOR_M
#undef HMATRIX_OPERATOR_N
/**/
#define HMATRIX_OPERATOR_M	4
#define HMATRIX_OPERATOR_N	5

#include "Hubris/HMatrix/HMatrixOperatorImpMultiplication.hxx"

#undef HMATRIX_OPERATOR_M
#undef HMATRIX_OPERATOR_N
/**/

#define HMATRIX_OPERATOR_M	5
#define HMATRIX_OPERATOR_N	5

#include "Hubris/HMatrix/HMatrixOperatorImpMultiplication.hxx"

#undef HMATRIX_OPERATOR_M
#undef HMATRIX_OPERATOR_N
/**/
