#file: Coretech/Code/Pride/PTestbed/SConscript


###########################################
# import

import os
from extras.extras_dictionary import GetArrayFromDictionary

Import( "env" )
env = env.Clone()


###########################################
# local varaibles

translationUnitName = 'PTestbed'
translationUnitProjectName = translationUnitName + env['MSVSPROJECTSUFFIX']
translationUnitSolutionName = translationUnitName + env['MSVSSOLUTIONSUFFIX']

#src files  
sourceFileDict = {
  'Private' : [
    'PTestbedAnimation.cpp',
    'PTestbedAnimation.h',
    'PTestbedBounds.cpp',
    'PTestbedBounds.h',    
    'PTestbedColour.cpp',
    'PTestbedColour.h',    
    'PTestbedConvexHull.cpp',
    'PTestbedConvexHull.h',    
    'PTestbedConvexHullGenerate.cpp',
    'PTestbedConvexHullGenerate.h',    
    'PTestbedGeometry.cpp',
    'PTestbedGeometry.h',
    'PTestbedImage.cpp',
    'PTestbedImage.h',
    'PTestbedIntersection.cpp',
    'PTestbedIntersection.h',
    'PTestbedLine.cpp',
    'PTestbedLine.h',    
    'PTestbedMaterial.cpp',
    'PTestbedMaterial.h',
    'PTestbedMesh.cpp',
    'PTestbedMesh.h',
    'PTestbedPlane.cpp',
    'PTestbedPlane.h',    
    'PTestbedSphere.cpp',
    'PTestbedSphere.h', 
    'PTestbedUnitVector.cpp',
    'PTestbedUnitVector.h',    
    ],
  '' : [
    'PTestbed_Import.h',
    'PTestbed.cpp',
    'PTestbed.h',
    'SConscript'
    ],
  }

######################################
#adjust our env

if env.get( 'TARGET_DEBUG', False ):
  env[ 'PDB' ] = translationUnitName + '.pdb'

######################################
#build exe alias( 'build' )

build = env.BuildMsvs(
  target = translationUnitName + '.exe',
  source = [ 
    translationUnitSolutionName,
    env.File( "${BUILD_DIR}/Code/Lib/Hubris.Lib" ),  
    env.File( "${BUILD_DIR}/Code/Lib/Pride.Lib" ),  
    ],
  sourceFile = env.File( '#Code/Pride/PTestbed/' + translationUnitSolutionName ),
  projectName = translationUnitName,
  )  
env.Alias( 'build', build )


######################################
#run testbed exe alias( 'testbed' )

if 'RunTestbed' in env['TOOLS']:
  testbed = env.RunTestbed(
    target = translationUnitName + '.txt',
    source = translationUnitName + '.exe',
    )  
  env.Alias( 'testbed', testbed )

######################################
#build project

if 'CreateMsvsProject' in env['TOOLS']:
  project = env.CreateMsvsProject(
    target = translationUnitProjectName,
    source = [
      env.File( '${CODE_DIR}/Pride/PTestbed/Sconscript' ),
      ],         
    sourceProjectFiles = sourceFileDict,
    additionalIncludeDirectories = [ 
      "..\\.."
      ],    
    additionalDependencies = [ 
      "Hubris.lib", 
      "Envy.lib",
      "Pride.lib",
      "Lust.lib",
      "TinyXml.lib",
      ],
    additionalLibraryDirectories = [ 
      env.Dir( '${BUILD_DIR}/Code/Lib' ).abspath,
      env.Dir( '${BUILD_DIR}/ThirdParty/Lib' ).abspath,
      ],
    projectType = 'Win32Proj',
    buildConsole = True,
    multiThread = True,      
    buildBase = os.path.join( "..", "..", "..", env.Dir( '.' ).path ),
    )
  Clean( project, env.File( translationUnitProjectName ).srcnode() )
  env.Default( project )

######################################
#build solution (default)

if 'CreateMsvsSolution' in env['TOOLS']:
  solution = env.CreateMsvsSolution(
    target = translationUnitSolutionName,
    source = [
      translationUnitProjectName,
      ],
    sourceSolutionDependency = { 
      translationUnitProjectName : [
        "Hubris.vcproj",
        "Envy.vcproj",
        "Pride.vcproj",
        "Lust.vcproj",
        "TinyXml.vcproj",
        ],
        
      "..\\..\\Hubris\\Hubris.vcproj" : [
        ],

      "..\\..\\Envy\\Envy.vcproj" : [
        ],

      "..\\..\\Lust\\Lust.vcproj" : [
        ],
        
      "..\\Pride.vcproj" : [
        ],
        
      "..\\..\\..\\ThirdParty\\TinyXml\\TinyXml.vcproj" : [
        ],        
      },
    solutionItemArray = [
      "SConscript",
      "..\\..\\..\\SolutionItems\\code_standard.txt",   
      "..\\..\\..\\SolutionItems\\todo.txt",   
      "..\\..\\..\\SolutionItems\\plan.txt",      
      ],

    )
  env.Clean( solution, env.File( translationUnitSolutionName ).srcnode() )  
  env.Default( solution )
        
#end file