//file: Hubris/HType/HTypeList.h
#ifndef _H_TYPE_LIST_H_
#define _H_TYPE_LIST_H_


//#include "Hubris/HType/HTypeNone.h"

namespace Hubris
{
	//concept taken from loki
	template< class IN_CLASS_A, class IN_CLASS_B > class HTypeList
	{
	public:
		typedef IN_CLASS_A Head; // a class or HTypeNone
		typedef IN_CLASS_B Tail; // a HTypeList or HTypeNone
	};

	class HTypeNone;
};

#define HTYPE_LIST_APPEND( IN_CLASS_A, IN_TYPE_LIST ) \
	Hubris::HTypeList< IN_CLASS_A, IN_TYPE_LIST >

#define HTYPE_LIST_0( )	\
	Hubris::HTypeList< Hubris::HTypeNone, Hubris::HTypeNone >

#define HTYPE_LIST_1( IN_CLASS_A )	\
	Hubris::HTypeList< IN_CLASS_A, Hubris::HTypeNone >

#define HTYPE_LIST_2( IN_CLASS_A, IN_CLASS_B )	\
	Hubris::HTypeList< IN_CLASS_B, HTYPE_LIST_1( IN_CLASS_A ) >

#define HTYPE_LIST_3( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C )	\
	Hubris::HTypeList< IN_CLASS_C, HTYPE_LIST_2( IN_CLASS_A, IN_CLASS_B ) >

#define HTYPE_LIST_4( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D )	\
	Hubris::HTypeList< IN_CLASS_D, HTYPE_LIST_3( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C ) >

#define HTYPE_LIST_5( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E )	\
	Hubris::HTypeList< IN_CLASS_E, HTYPE_LIST_4( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D ) >

#define HTYPE_LIST_6( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F )	\
	Hubris::HTypeList< IN_CLASS_F, HTYPE_LIST_5( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E ) >

#define HTYPE_LIST_7( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G )	\
	Hubris::HTypeList< IN_CLASS_G, HTYPE_LIST_6( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F ) >

#define HTYPE_LIST_8( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H )	\
	Hubris::HTypeList< IN_CLASS_H, HTYPE_LIST_7( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G ) >

#define HTYPE_LIST_9( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, IN_CLASS_I )	\
	Hubris::HTypeList< IN_CLASS_I, HTYPE_LIST_8( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H ) >

#define HTYPE_LIST_10( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
		IN_CLASS_I, IN_CLASS_J )	\
	Hubris::HTypeList< IN_CLASS_J, HTYPE_LIST_9( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
		IN_CLASS_G, IN_CLASS_H, IN_CLASS_I ) >

#define HTYPE_LIST_11( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
		IN_CLASS_I, IN_CLASS_J, IN_CLASS_K )	\
	Hubris::HTypeList< IN_CLASS_K, HTYPE_LIST_10( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
		IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J ) >

#define HTYPE_LIST_12( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
		IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L )	\
	Hubris::HTypeList< IN_CLASS_L, HTYPE_LIST_11( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
		IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K ) >

#define HTYPE_LIST_13( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
		IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M )	\
	Hubris::HTypeList< IN_CLASS_M, HTYPE_LIST_12( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
		IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L ) >

#define HTYPE_LIST_14( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
		IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N )	\
	Hubris::HTypeList< IN_CLASS_N, HTYPE_LIST_13( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
		IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M ) >

#define HTYPE_LIST_15( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
		IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O )	\
	Hubris::HTypeList< IN_CLASS_O, HTYPE_LIST_14( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
		IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N ) >

#define HTYPE_LIST_16( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
		IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P )	\
	Hubris::HTypeList< IN_CLASS_P, HTYPE_LIST_15( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
		IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O ) >

#define HTYPE_LIST_17( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
		IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q )	\
	Hubris::HTypeList< IN_CLASS_Q, HTYPE_LIST_16( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
		IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P ) >

#define HTYPE_LIST_18( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
		IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q, IN_CLASS_R )	\
	Hubris::HTypeList< IN_CLASS_R, HTYPE_LIST_17( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
		IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q ) >

#define HTYPE_LIST_19( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
		IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q, IN_CLASS_R, IN_CLASS_S )	\
	Hubris::HTypeList< IN_CLASS_S, HTYPE_LIST_18( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
		IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q, IN_CLASS_R ) >

#define HTYPE_LIST_20( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
		IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q, IN_CLASS_R, \
		IN_CLASS_S, IN_CLASS_T )	\
	Hubris::HTypeList< IN_CLASS_T, HTYPE_LIST_19( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
		IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, \
		IN_CLASS_Q, IN_CLASS_R, IN_CLASS_S ) >

#define HTYPE_LIST_21( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
		IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q, IN_CLASS_R, \
		IN_CLASS_S, IN_CLASS_T, IN_CLASS_U )	\
	Hubris::HTypeList< IN_CLASS_U, HTYPE_LIST_20( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
		IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, \
		IN_CLASS_Q, IN_CLASS_R, IN_CLASS_S, IN_CLASS_T ) >

#define HTYPE_LIST_22( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
		IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q, IN_CLASS_R, \
		IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V )	\
	Hubris::HTypeList< IN_CLASS_V, HTYPE_LIST_21( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
		IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, \
		IN_CLASS_Q, IN_CLASS_R, IN_CLASS_S, IN_CLASS_T, IN_CLASS_U ) >

#define HTYPE_LIST_23( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
		IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q, IN_CLASS_R, \
		IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W )	\
	Hubris::HTypeList< IN_CLASS_W, HTYPE_LIST_22( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
		IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, \
		IN_CLASS_Q, IN_CLASS_R, IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V ) >

#define HTYPE_LIST_24( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
		IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q, IN_CLASS_R, \
		IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X )	\
	Hubris::HTypeList< IN_CLASS_X, HTYPE_LIST_23( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
		IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, \
		IN_CLASS_Q, IN_CLASS_R, IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W ) >

#define HTYPE_LIST_25( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
		IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q, IN_CLASS_R, \
		IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y )	\
	Hubris::HTypeList< IN_CLASS_Y, HTYPE_LIST_24( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
		IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, \
		IN_CLASS_Q, IN_CLASS_R, IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X ) >

#define HTYPE_LIST_26( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
		IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q, IN_CLASS_R, \
		IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z )	\
	Hubris::HTypeList< IN_CLASS_Z, HTYPE_LIST_25( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
		IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, \
		IN_CLASS_Q, IN_CLASS_R, IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y ) >

#define HTYPE_LIST_27( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
	IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q, IN_CLASS_R, \
	IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, IN_CLASS_A2 )	\
	Hubris::HTypeList< IN_CLASS_A2, HTYPE_LIST_26( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
	IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, \
	IN_CLASS_Q, IN_CLASS_R, IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z ) >

#define HTYPE_LIST_28( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
	IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q, IN_CLASS_R, \
	IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, IN_CLASS_A2, IN_CLASS_B2 )	\
	Hubris::HTypeList< IN_CLASS_B2, HTYPE_LIST_27( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
	IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, \
	IN_CLASS_Q, IN_CLASS_R, IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, \
	IN_CLASS_A2 ) >

#define HTYPE_LIST_29( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
	IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q, IN_CLASS_R, \
	IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, IN_CLASS_A2, IN_CLASS_B2, \
	IN_CLASS_C2 ) \
	Hubris::HTypeList< IN_CLASS_C2, HTYPE_LIST_28( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
	IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, \
	IN_CLASS_Q, IN_CLASS_R, IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, \
	IN_CLASS_A2, IN_CLASS_B2 ) >

#define HTYPE_LIST_30( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
	IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q, IN_CLASS_R, \
	IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, IN_CLASS_A2, IN_CLASS_B2, \
	IN_CLASS_C2, IN_CLASS_D2 ) \
	Hubris::HTypeList< IN_CLASS_D2, HTYPE_LIST_29( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
	IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, \
	IN_CLASS_Q, IN_CLASS_R, IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, \
	IN_CLASS_A2, IN_CLASS_B2, IN_CLASS_C2 ) >

#define HTYPE_LIST_31( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
	IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q, IN_CLASS_R, \
	IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, IN_CLASS_A2, IN_CLASS_B2, \
	IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2 ) \
	Hubris::HTypeList< IN_CLASS_E2, HTYPE_LIST_30( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
	IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, \
	IN_CLASS_Q, IN_CLASS_R, IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, \
	IN_CLASS_A2, IN_CLASS_B2, IN_CLASS_C2, IN_CLASS_D2 ) >

#define HTYPE_LIST_32( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
	IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q, IN_CLASS_R, \
	IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, IN_CLASS_A2, IN_CLASS_B2, \
	IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2 ) \
	Hubris::HTypeList< IN_CLASS_F2, HTYPE_LIST_31( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
	IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, \
	IN_CLASS_Q, IN_CLASS_R, IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, \
	IN_CLASS_A2, IN_CLASS_B2, IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2 ) >

#define HTYPE_LIST_33( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
	IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q, IN_CLASS_R, \
	IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, IN_CLASS_A2, IN_CLASS_B2, \
	IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2 ) \
	Hubris::HTypeList< IN_CLASS_G2, HTYPE_LIST_32( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
	IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, \
	IN_CLASS_Q, IN_CLASS_R, IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, \
	IN_CLASS_A2, IN_CLASS_B2, IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2 ) >

#define HTYPE_LIST_34( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
	IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q, IN_CLASS_R, \
	IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, IN_CLASS_A2, IN_CLASS_B2, \
	IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2, IN_CLASS_H2 ) \
	Hubris::HTypeList< IN_CLASS_H2, HTYPE_LIST_33( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
	IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, \
	IN_CLASS_Q, IN_CLASS_R, IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, \
	IN_CLASS_A2, IN_CLASS_B2, IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2 ) >

#define HTYPE_LIST_35( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
	IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q, IN_CLASS_R, \
	IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, IN_CLASS_A2, IN_CLASS_B2, \
	IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2, IN_CLASS_H2, IN_CLASS_I2 ) \
	Hubris::HTypeList< IN_CLASS_I2, HTYPE_LIST_34( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
	IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, \
	IN_CLASS_Q, IN_CLASS_R, IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, \
	IN_CLASS_A2, IN_CLASS_B2, IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2, IN_CLASS_H2 ) >

#define HTYPE_LIST_36( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
	IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q, IN_CLASS_R, \
	IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, IN_CLASS_A2, IN_CLASS_B2, \
	IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2, IN_CLASS_H2, IN_CLASS_I2, IN_CLASS_J2 ) \
	Hubris::HTypeList< IN_CLASS_J2, HTYPE_LIST_35( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
	IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, \
	IN_CLASS_Q, IN_CLASS_R, IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, \
	IN_CLASS_A2, IN_CLASS_B2, IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2, IN_CLASS_H2, IN_CLASS_I2 ) >

#define HTYPE_LIST_37( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
	IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q, IN_CLASS_R, \
	IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, IN_CLASS_A2, IN_CLASS_B2, \
	IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2, IN_CLASS_H2, IN_CLASS_I2, IN_CLASS_J2, IN_CLASS_K2 ) \
	Hubris::HTypeList< IN_CLASS_K2, HTYPE_LIST_36( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
	IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, \
	IN_CLASS_Q, IN_CLASS_R, IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, \
	IN_CLASS_A2, IN_CLASS_B2, IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2, IN_CLASS_H2, IN_CLASS_I2, \
	IN_CLASS_J2 ) >

#define HTYPE_LIST_38( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
	IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q, IN_CLASS_R, \
	IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, IN_CLASS_A2, IN_CLASS_B2, \
	IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2, IN_CLASS_H2, IN_CLASS_I2, IN_CLASS_J2, IN_CLASS_K2, \
	IN_CLASS_L2 ) \
	Hubris::HTypeList< IN_CLASS_L2, HTYPE_LIST_37( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
	IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, \
	IN_CLASS_Q, IN_CLASS_R, IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, \
	IN_CLASS_A2, IN_CLASS_B2, IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2, IN_CLASS_H2, IN_CLASS_I2, \
	IN_CLASS_J2, IN_CLASS_K2 ) >

#define HTYPE_LIST_39( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
	IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q, IN_CLASS_R, \
	IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, IN_CLASS_A2, IN_CLASS_B2, \
	IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2, IN_CLASS_H2, IN_CLASS_I2, IN_CLASS_J2, IN_CLASS_K2, \
	IN_CLASS_L2, IN_CLASS_M2 ) \
	Hubris::HTypeList< IN_CLASS_M2, HTYPE_LIST_38( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
	IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, \
	IN_CLASS_Q, IN_CLASS_R, IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, \
	IN_CLASS_A2, IN_CLASS_B2, IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2, IN_CLASS_H2, IN_CLASS_I2, \
	IN_CLASS_J2, IN_CLASS_K2, IN_CLASS_L2 ) >

#define HTYPE_LIST_40( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
	IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q, IN_CLASS_R, \
	IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, IN_CLASS_A2, IN_CLASS_B2, \
	IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2, IN_CLASS_H2, IN_CLASS_I2, IN_CLASS_J2, IN_CLASS_K2, \
	IN_CLASS_L2, IN_CLASS_M2, IN_CLASS_N2 ) \
	Hubris::HTypeList< IN_CLASS_N2, HTYPE_LIST_39( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
	IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, \
	IN_CLASS_Q, IN_CLASS_R, IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, \
	IN_CLASS_A2, IN_CLASS_B2, IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2, IN_CLASS_H2, IN_CLASS_I2, \
	IN_CLASS_J2, IN_CLASS_K2, IN_CLASS_L2, IN_CLASS_M2 ) >

#define HTYPE_LIST_41( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
	IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q, IN_CLASS_R, \
	IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, IN_CLASS_A2, IN_CLASS_B2, \
	IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2, IN_CLASS_H2, IN_CLASS_I2, IN_CLASS_J2, IN_CLASS_K2, \
	IN_CLASS_L2, IN_CLASS_M2, IN_CLASS_N2, IN_CLASS_O2 ) \
	Hubris::HTypeList< IN_CLASS_O2, HTYPE_LIST_40( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
	IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, \
	IN_CLASS_Q, IN_CLASS_R, IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, \
	IN_CLASS_A2, IN_CLASS_B2, IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2, IN_CLASS_H2, IN_CLASS_I2, \
	IN_CLASS_J2, IN_CLASS_K2, IN_CLASS_L2, IN_CLASS_M2, IN_CLASS_N2 ) >

#define HTYPE_LIST_42( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
	IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q, IN_CLASS_R, \
	IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, IN_CLASS_A2, IN_CLASS_B2, \
	IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2, IN_CLASS_H2, IN_CLASS_I2, IN_CLASS_J2, IN_CLASS_K2, \
	IN_CLASS_L2, IN_CLASS_M2, IN_CLASS_N2, IN_CLASS_O2, IN_CLASS_P2 ) \
	Hubris::HTypeList< IN_CLASS_P2, HTYPE_LIST_41( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
	IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, \
	IN_CLASS_Q, IN_CLASS_R, IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, \
	IN_CLASS_A2, IN_CLASS_B2, IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2, IN_CLASS_H2, IN_CLASS_I2, \
	IN_CLASS_J2, IN_CLASS_K2, IN_CLASS_L2, IN_CLASS_M2, IN_CLASS_N2, IN_CLASS_O2 ) >

#define HTYPE_LIST_43( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
	IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q, IN_CLASS_R, \
	IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, IN_CLASS_A2, IN_CLASS_B2, \
	IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2, IN_CLASS_H2, IN_CLASS_I2, IN_CLASS_J2, IN_CLASS_K2, \
	IN_CLASS_L2, IN_CLASS_M2, IN_CLASS_N2, IN_CLASS_O2, IN_CLASS_P2, IN_CLASS_Q2 ) \
	Hubris::HTypeList< IN_CLASS_Q2, HTYPE_LIST_42( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
	IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, \
	IN_CLASS_Q, IN_CLASS_R, IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, \
	IN_CLASS_A2, IN_CLASS_B2, IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2, IN_CLASS_H2, IN_CLASS_I2, \
	IN_CLASS_J2, IN_CLASS_K2, IN_CLASS_L2, IN_CLASS_M2, IN_CLASS_N2, IN_CLASS_O2, IN_CLASS_P2 ) >

#define HTYPE_LIST_44( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
	IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q, IN_CLASS_R, \
	IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, IN_CLASS_A2, IN_CLASS_B2, \
	IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2, IN_CLASS_H2, IN_CLASS_I2, IN_CLASS_J2, IN_CLASS_K2, \
	IN_CLASS_L2, IN_CLASS_M2, IN_CLASS_N2, IN_CLASS_O2, IN_CLASS_P2, IN_CLASS_Q2, IN_CLASS_R2 ) \
	Hubris::HTypeList< IN_CLASS_R2, HTYPE_LIST_43( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
	IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, \
	IN_CLASS_Q, IN_CLASS_R, IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, \
	IN_CLASS_A2, IN_CLASS_B2, IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2, IN_CLASS_H2, IN_CLASS_I2, \
	IN_CLASS_J2, IN_CLASS_K2, IN_CLASS_L2, IN_CLASS_M2, IN_CLASS_N2, IN_CLASS_O2, IN_CLASS_P2, IN_CLASS_Q2 ) >

#define HTYPE_LIST_45( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
	IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q, IN_CLASS_R, \
	IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, IN_CLASS_A2, IN_CLASS_B2, \
	IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2, IN_CLASS_H2, IN_CLASS_I2, IN_CLASS_J2, IN_CLASS_K2, \
	IN_CLASS_L2, IN_CLASS_M2, IN_CLASS_N2, IN_CLASS_O2, IN_CLASS_P2, IN_CLASS_Q2, IN_CLASS_R2, IN_CLASS_S2 ) \
	Hubris::HTypeList< IN_CLASS_S2, HTYPE_LIST_44( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
	IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, \
	IN_CLASS_Q, IN_CLASS_R, IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, \
	IN_CLASS_A2, IN_CLASS_B2, IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2, IN_CLASS_H2, IN_CLASS_I2, \
	IN_CLASS_J2, IN_CLASS_K2, IN_CLASS_L2, IN_CLASS_M2, IN_CLASS_N2, IN_CLASS_O2, IN_CLASS_P2, IN_CLASS_Q2, IN_CLASS_R2 ) >

#define HTYPE_LIST_46( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
	IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q, IN_CLASS_R, \
	IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, IN_CLASS_A2, IN_CLASS_B2, \
	IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2, IN_CLASS_H2, IN_CLASS_I2, IN_CLASS_J2, IN_CLASS_K2, \
	IN_CLASS_L2, IN_CLASS_M2, IN_CLASS_N2, IN_CLASS_O2, IN_CLASS_P2, IN_CLASS_Q2, IN_CLASS_R2, IN_CLASS_S2, IN_CLASS_T2 ) \
	Hubris::HTypeList< IN_CLASS_T2, HTYPE_LIST_45( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
	IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, \
	IN_CLASS_Q, IN_CLASS_R, IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, \
	IN_CLASS_A2, IN_CLASS_B2, IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2, IN_CLASS_H2, IN_CLASS_I2, \
	IN_CLASS_J2, IN_CLASS_K2, IN_CLASS_L2, IN_CLASS_M2, IN_CLASS_N2, IN_CLASS_O2, IN_CLASS_P2, IN_CLASS_Q2, IN_CLASS_R2, \
	IN_CLASS_S2 ) >

#define HTYPE_LIST_47( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
	IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q, IN_CLASS_R, \
	IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, IN_CLASS_A2, IN_CLASS_B2, \
	IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2, IN_CLASS_H2, IN_CLASS_I2, IN_CLASS_J2, IN_CLASS_K2, \
	IN_CLASS_L2, IN_CLASS_M2, IN_CLASS_N2, IN_CLASS_O2, IN_CLASS_P2, IN_CLASS_Q2, IN_CLASS_R2, IN_CLASS_S2, IN_CLASS_T2, \
	IN_CLASS_U2 ) \
	Hubris::HTypeList< IN_CLASS_U2, HTYPE_LIST_46( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
	IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, \
	IN_CLASS_Q, IN_CLASS_R, IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, \
	IN_CLASS_A2, IN_CLASS_B2, IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2, IN_CLASS_H2, IN_CLASS_I2, \
	IN_CLASS_J2, IN_CLASS_K2, IN_CLASS_L2, IN_CLASS_M2, IN_CLASS_N2, IN_CLASS_O2, IN_CLASS_P2, IN_CLASS_Q2, IN_CLASS_R2, \
	IN_CLASS_S2, IN_CLASS_T2 ) >

#define HTYPE_LIST_48( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
	IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q, IN_CLASS_R, \
	IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, IN_CLASS_A2, IN_CLASS_B2, \
	IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2, IN_CLASS_H2, IN_CLASS_I2, IN_CLASS_J2, IN_CLASS_K2, \
	IN_CLASS_L2, IN_CLASS_M2, IN_CLASS_N2, IN_CLASS_O2, IN_CLASS_P2, IN_CLASS_Q2, IN_CLASS_R2, IN_CLASS_S2, IN_CLASS_T2, \
	IN_CLASS_U2, IN_CLASS_V2 ) \
	Hubris::HTypeList< IN_CLASS_V2, HTYPE_LIST_47( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
	IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, \
	IN_CLASS_Q, IN_CLASS_R, IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, \
	IN_CLASS_A2, IN_CLASS_B2, IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2, IN_CLASS_H2, IN_CLASS_I2, \
	IN_CLASS_J2, IN_CLASS_K2, IN_CLASS_L2, IN_CLASS_M2, IN_CLASS_N2, IN_CLASS_O2, IN_CLASS_P2, IN_CLASS_Q2, IN_CLASS_R2, \
	IN_CLASS_S2, IN_CLASS_T2, IN_CLASS_U2 ) >

#define HTYPE_LIST_49( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
	IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q, IN_CLASS_R, \
	IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, IN_CLASS_A2, IN_CLASS_B2, \
	IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2, IN_CLASS_H2, IN_CLASS_I2, IN_CLASS_J2, IN_CLASS_K2, \
	IN_CLASS_L2, IN_CLASS_M2, IN_CLASS_N2, IN_CLASS_O2, IN_CLASS_P2, IN_CLASS_Q2, IN_CLASS_R2, IN_CLASS_S2, IN_CLASS_T2, \
	IN_CLASS_U2, IN_CLASS_V2, IN_CLASS_W2 ) \
	Hubris::HTypeList< IN_CLASS_W2, HTYPE_LIST_48( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
	IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, \
	IN_CLASS_Q, IN_CLASS_R, IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, \
	IN_CLASS_A2, IN_CLASS_B2, IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2, IN_CLASS_H2, IN_CLASS_I2, \
	IN_CLASS_J2, IN_CLASS_K2, IN_CLASS_L2, IN_CLASS_M2, IN_CLASS_N2, IN_CLASS_O2, IN_CLASS_P2, IN_CLASS_Q2, IN_CLASS_R2, \
	IN_CLASS_S2, IN_CLASS_T2, IN_CLASS_U2, IN_CLASS_V2 ) >

#define HTYPE_LIST_50( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
	IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q, IN_CLASS_R, \
	IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, IN_CLASS_A2, IN_CLASS_B2, \
	IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2, IN_CLASS_H2, IN_CLASS_I2, IN_CLASS_J2, IN_CLASS_K2, \
	IN_CLASS_L2, IN_CLASS_M2, IN_CLASS_N2, IN_CLASS_O2, IN_CLASS_P2, IN_CLASS_Q2, IN_CLASS_R2, IN_CLASS_S2, IN_CLASS_T2, \
	IN_CLASS_U2, IN_CLASS_V2, IN_CLASS_W2, IN_CLASS_X2 ) \
	Hubris::HTypeList< IN_CLASS_X2, HTYPE_LIST_49( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
	IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, \
	IN_CLASS_Q, IN_CLASS_R, IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, \
	IN_CLASS_A2, IN_CLASS_B2, IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2, IN_CLASS_H2, IN_CLASS_I2, \
	IN_CLASS_J2, IN_CLASS_K2, IN_CLASS_L2, IN_CLASS_M2, IN_CLASS_N2, IN_CLASS_O2, IN_CLASS_P2, IN_CLASS_Q2, IN_CLASS_R2, \
	IN_CLASS_S2, IN_CLASS_T2, IN_CLASS_U2, IN_CLASS_V2, IN_CLASS_W2 ) >

#define HTYPE_LIST_51( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
	IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q, IN_CLASS_R, \
	IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, IN_CLASS_A2, IN_CLASS_B2, \
	IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2, IN_CLASS_H2, IN_CLASS_I2, IN_CLASS_J2, IN_CLASS_K2, \
	IN_CLASS_L2, IN_CLASS_M2, IN_CLASS_N2, IN_CLASS_O2, IN_CLASS_P2, IN_CLASS_Q2, IN_CLASS_R2, IN_CLASS_S2, IN_CLASS_T2, \
	IN_CLASS_U2, IN_CLASS_V2, IN_CLASS_W2, IN_CLASS_X2, IN_CLASS_Y2 ) \
	Hubris::HTypeList< IN_CLASS_Y2, HTYPE_LIST_50( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
	IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, \
	IN_CLASS_Q, IN_CLASS_R, IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, \
	IN_CLASS_A2, IN_CLASS_B2, IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2, IN_CLASS_H2, IN_CLASS_I2, \
	IN_CLASS_J2, IN_CLASS_K2, IN_CLASS_L2, IN_CLASS_M2, IN_CLASS_N2, IN_CLASS_O2, IN_CLASS_P2, IN_CLASS_Q2, IN_CLASS_R2, \
	IN_CLASS_S2, IN_CLASS_T2, IN_CLASS_U2, IN_CLASS_V2, IN_CLASS_W2, IN_CLASS_X2 ) >

#define HTYPE_LIST_52( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, IN_CLASS_G, IN_CLASS_H, \
	IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, IN_CLASS_Q, IN_CLASS_R, \
	IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, IN_CLASS_A2, IN_CLASS_B2, \
	IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2, IN_CLASS_H2, IN_CLASS_I2, IN_CLASS_J2, IN_CLASS_K2, \
	IN_CLASS_L2, IN_CLASS_M2, IN_CLASS_N2, IN_CLASS_O2, IN_CLASS_P2, IN_CLASS_Q2, IN_CLASS_R2, IN_CLASS_S2, IN_CLASS_T2, \
	IN_CLASS_U2, IN_CLASS_V2, IN_CLASS_W2, IN_CLASS_X2, IN_CLASS_Y2, IN_CLASS_Z2 ) \
	Hubris::HTypeList< IN_CLASS_Z2, HTYPE_LIST_51( IN_CLASS_A, IN_CLASS_B, IN_CLASS_C, IN_CLASS_D, IN_CLASS_E, IN_CLASS_F, \
	IN_CLASS_G, IN_CLASS_H, IN_CLASS_I, IN_CLASS_J, IN_CLASS_K, IN_CLASS_L, IN_CLASS_M, IN_CLASS_N, IN_CLASS_O, IN_CLASS_P, \
	IN_CLASS_Q, IN_CLASS_R, IN_CLASS_S, IN_CLASS_T, IN_CLASS_U, IN_CLASS_V, IN_CLASS_W, IN_CLASS_X, IN_CLASS_Y, IN_CLASS_Z, \
	IN_CLASS_A2, IN_CLASS_B2, IN_CLASS_C2, IN_CLASS_D2, IN_CLASS_E2, IN_CLASS_F2, IN_CLASS_G2, IN_CLASS_H2, IN_CLASS_I2, \
	IN_CLASS_J2, IN_CLASS_K2, IN_CLASS_L2, IN_CLASS_M2, IN_CLASS_N2, IN_CLASS_O2, IN_CLASS_P2, IN_CLASS_Q2, IN_CLASS_R2, \
	IN_CLASS_S2, IN_CLASS_T2, IN_CLASS_U2, IN_CLASS_V2, IN_CLASS_W2, IN_CLASS_X2, IN_CLASS_Y2 ) >


#define HTYPE_LIST_MAX 53


#endif // _H_TYPE_LIST_H_